// Daniel McPherson, All Rights Reserved

#pragma once

#include "CoreMinimal.h"
#include "CommonListView.h"
#include "K2HCommonListView.generated.h"

class UDataAsset_DataListEntryMapping;
/**
 * Provides overrided functionality to provide our own Entry widget to be generated by the List View
 */
UCLASS()
class K2H_RPG_API UK2HCommonListView : public UCommonListView
{
	GENERATED_BODY()

protected:

	//~ Begin UCommonListView Interface
	//Uses UDataAsset_DataListEntryMapping to determine what widget to generate int he List View.
	virtual UUserWidget& OnGenerateEntryWidgetInternal(UObject* Item, TSubclassOf<UUserWidget> DesiredEntryClass, 
		const TSharedRef<STableViewBase>& OwnerTable) override;
	//~ End UCommonListView Interface

private:


//Called at the end of Widget Blueprint compilation.
//Allows UMG elements to evaluate their default states and determine whether they are acceptable.
//To trigger compilation failure, add an error to the log. Warnings and notes will be visible, 
// but will not cause compiles to fail. This is where we log errors for when data asset is not assigned
	//~ Begin UWidget Interface
#if WITH_EDITOR	
	virtual void ValidateCompiledDefaults(class IWidgetCompilerLog& CompileLog) const override;
#endif
	//~ End UWidget Interface

	//map for accessing widget classes to be generated based off of source object data types
	UPROPERTY(EditAnywhere, Category = "K2H List View Settings")
	UDataAsset_DataListEntryMapping* DataListEntryMapping;
};
